In [10]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.datasets import load_iris

data = np.array([[1 , -1, 2], 
                [2, 0, 0], 
                [0, 1, -1]])
print(data)

scaler = MinMaxScaler(feature_range=(0, 1))
data_escalada = scaler.fit_transform(data)
print(data_escalada)

[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [11]:

iris = load_iris()
X = iris.data
X_escalado = scaler.fit_transform(X)

print(X[:5])
print(X_escalado[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [12]:
scaler2 = StandardScaler()
data_escalada2 = scaler2.fit_transform(data)
print(data_escalada2)   

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [13]:
print(np.std(data_escalada2))

1.0


In [15]:
categorias = np.array([["rojo"], ["verde"], ["azul"], ["verde"], ["verde"], ["azul"]])
encoder = OneHotEncoder(sparse_output=False)
data_codificada = encoder.fit_transform(categorias)
print(data_codificada)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
